setting:
  name: "sanity_test"
  output_root: "./experiments"
  pc_path: "/home/UNT/md0708/kitti/data_odometry_velodyne/dataset/sequences/00/velodyne"
  pose_path: "/home/UNT/md0708/kitti/data_odometry_poses/dataset/poses/00.txt" 

process:
  max_range_m: 60.0
tracker:
  iter_n: 20
eval:
  wandb_vis_on: True # log to wandb or not
  o3d_vis_on: True # visualize the mapping or not
  silence_log: False # output the logs or not
  sensor_cad_path: ./cad/kitti_car.ply
  save_map: True
  save_mesh: True
